### ISSUE TITLE
Core libraries seem to be unknown (e.g. ofxPoco)

### ISSUE THREAD

**Issue by bakercp** [thomasgeissl/ofPackageManager#4]
When installing libraries that depend on core addons, problems ensue.  For example, when running:

```
ofPackageManager install -g ofxHTTP
```
 you get
```
[ notice ] install: trying to find ofxPoco in the database. 
[  error ] search: Unfortunately this package was not found in the database. 
But it is probably available on github. Wanna give it a try? [y|n] (y) ^[[B
```

If you try to install it directly:
```
ofPackageManager install -g ofxPoco
```

it doesn't seem to recognized ...

```
bakercp:~/Desktop/openFrameworks$ ofPackageManager 
[  error ] ofPackageManager: unkown task  
[ notice ] ofPackageManager: info 
[ notice ] version: 0.0.9
[ notice ] path: TODO 
[ notice ] global config path: /Users/bakercp/.ofPackageManager.json 
[ warning] TODO: print manual 
[ notice ] Thanks for using ofPackageManager. If you find a bug then please report it on the github issue tracker (https://github.com/thomasgeissl/ofPackageManager/issues). See you soon. 
```

**Comment by thomasgeissl** [comment]
I guess I could check first if the add-on is already installed. Or somewhere store which adding are core addons. Not sure how to maintain this for different oF versions.
I will have a look later.
Thanks for reporting.

**Comment by thomasgeissl** [comment]
i cannot reproduce the unkown task.
```
ster ●  ofPackageManager install -g ofxPoco
[ notice ] install: trying to find ofxPoco in the database.
[  error ] search: Unfortunately this package was not found in the database.
But it is probably available on github. Wanna give it a try? [y|n] (y) y
[ notice ] search: The following repositories containofxPoco:
0: trentbrooks/ofxPocoNetwork
1: Venetian/ofxPocoEventTimer
2: Geistyp/ofxPocoDirectoryWatcher

Do you wanna install any of them? [y|n] (y) n
[ notice ] Thanks for using ofPackageManager. If you find a bug then please report it on the github issue tracker (https://github.com/thomasgeissl/ofPackageManager/issues). See you soon.
```

**Comment by thomasgeissl** [comment]
I just uploaded a fix. Would you mind checking if that works for you?
I assume that every directory inside the global addons directory which is not a valid git repo, is a core addon.
```brew upgrade ofpackagemanager``` should update it, if you installed it via brew.

**Comment by bakercp** [comment]
The unknown task issue is just what happens when you run it with no commands.

The fix seemed to solve the ofxPoco issue.  Thanks!  This is exciting!

**Comment by thomasgeissl** [comment]
Ah, I see. What would you expect as the default task? A proper error message?

**Comment by bakercp** [comment]
Maybe a list of valid tasks / commands?

**Comment by thomasgeissl** [comment]
i was thinking about the same. probably add it later.
thnkas
