### ISSUE TITLE
release a windows version

### ISSUE THREAD

**Issue by thomasgeissl** [thomasgeissl/ofPackageManager#76]
heyho @prisonerjohn,
if you have some time these days, could you do another windows release?
i did some changes, hope it still compiles fine on windows. i had troubles getting the libgit2 linking working.
there is also an electron frontend i wanna test it against. 
https://github.com/thomasgeissl/ofPackageManager-frontend
T

**Comment by prisonerjohn** [comment]
Hey! Sure ,I can take a look over the next couple of days. I'll keep you posted.

**Comment by thomasgeissl** [comment]
thanks a lot!

**Comment by prisonerjohn** [comment]
Hey @thomasgeissl, 

Got this to build but it's not finding the config file when I try to use the tool. I looked through the sources quickly and notices that when it creates a new file it is called [`ofPackageManager.cli.configjson`](https://github.com/thomasgeissl/ofPackageManager/blob/master/src/ofApp.cpp#L144), but when it checks if the file exists it is called [`ofPackageManager.cli.config.json`](https://github.com/thomasgeissl/ofPackageManager/blob/master/src/ofApp.cpp#L1004).

Is that a bug or am I reading this wrong?

**Comment by thomasgeissl** [comment]
thank you so much Elie.
this was definetely a bug. should be fixed now. v0.0.21
but also there is this line, which seems to be dangerous. it needs to detect if it is at the root directory, i dont know how it looks on windows fs, but i hope it shorter than 4 chars.
https://github.com/thomasgeissl/ofPackageManager/blob/master/src/ofApp.cpp#L898

**Comment by prisonerjohn** [comment]
Ok looks good! That line is fine, the root on Windows is something like `C:\` so it's only 3 characters.

Here is the package, I don't think I have the permissions to upload it directly on the Releases page: [ofPackageManager_win_0.0.21.zip](https://github.com/thomasgeissl/ofPackageManager/files/4568477/ofPackageManager_win_0.0.21.zip)

**Comment by thomasgeissl** [comment]
thank you so much. i owe you a beer.
i will test it with the the package manager frontend. hope that runs smoothly.

i could not find how to give you permissions. i thought you did a release last time.

**Comment by thomasgeissl** [comment]
i just did a windows release of the frontend.
will do a forum post soon.
https://github.com/thomasgeissl/ofPackageManager-frontend/releases/tag/0.0.21

in case you wanna try:
the steps are as follows.
1. download ofPackageManager cli and add it to your path: (https://github.com/thomasgeissl/ofPackageManager/releases)
1. configure ofPackageManager globally: `ofPackageManager config -g`
1. download or compile projectGenerator cli and add it your path (should be included in the packages, e.g. path/to/of_v0.11.0_vs2017_release/projectGenerator-vs/resources/app/app/projectGenerator.EXE)
1. download ofPackageManager-frontend and run it (https://github.com/thomasgeissl/ofPackageManager-frontend/releases)

**Comment by prisonerjohn** [comment]
Awesome I'll check it out. 
I thought I uploaded it directly last time too, maybe GitHub changed something.
